name: Purge Old ACR Images

on:
  schedule:
    - cron: "0 3 * * *"   # nightly at 3 AM UTC
  workflow_dispatch:       # allows manual trigger too

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Purge Old dev Images
        run: |
          az acr run --registry ${{ vars.ACR_NAME_DEV }} \
            --cmd "acr purge --filter 'status-app:.*' --ago 0d --keep 3 --untagged" /dev/null
      
      - name: Purge Old prod Images
        run: |
          az acr run --registry ${{ vars.ACR_NAME_PROD }} \
            --cmd "acr purge --filter 'status-app:.*' --ago 0d --keep 3 --untagged" /dev/null